name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: healthcare_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 5s --health-timeout 5s --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Prisma generate
        run: npm run db:generate
      - name: Prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/healthcare_test
        run: npx prisma migrate deploy
      - name: Seed database (basic)
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/healthcare_test
          NEXTAUTH_SECRET: testsecret
        run: node scripts/ci-seed-auth.js
      - name: Type check
        run: npm run type-check
      - name: Lint
        run: npm run lint || echo 'Lint warnings'
      - name: Build
        run: npm run build
      - name: Test patient service basic create/list
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/healthcare_test
          NEXTAUTH_SECRET: testsecret
        run: node scripts/ci-patient-basic.js
      - name: Start app (background)
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/healthcare_test
          NEXTAUTH_SECRET: testsecret
          NEXTAUTH_URL: http://localhost:3000
          OTEL_TRACING_DISABLED: '1'
        run: |
          nohup npm start >/dev/null 2>&1 &
          echo $! > app.pid
          echo "Waiting app..."
          for i in $(seq 1 30); do
            if curl -fsS http://localhost:3000/api/health >/dev/null 2>&1; then echo "App up"; break; fi; sleep 2; done
          curl -fsS http://localhost:3000/api/health || (echo 'App did not start' && exit 1)
      - name: RBAC & Auth HTTP tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/healthcare_test
          NEXTAUTH_SECRET: testsecret
          NEXTAUTH_URL: http://localhost:3000
        run: |
          node test-patients-auth.js
          node test-rbac-patients.js
      - name: Stop app
        if: always()
        run: |
          if [ -f app.pid ]; then kill $(cat app.pid) || true; fi
      - name: Security quick audit
        run: npm run security:quick-audit
