name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: healthcare_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 5s --health-timeout 5s --health-retries 10
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/healthcare_test
      NEXTAUTH_SECRET: testsecret
      NEXTAUTH_URL: http://localhost:3000
      OTEL_TRACING_DISABLED: '1'
      DISABLE_REDIS: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma client
        run: npm run db:generate
      - name: Apply migrations
        run: npx prisma migrate deploy
      - name: Seed auth users
        run: node scripts/ci-seed-auth.js
      - name: Type check
        run: npm run type-check
      - name: Lint (non blocking)
        run: npm run lint || echo 'Lint warnings'
      - name: Build
        run: npm run build
      - name: Basic DB test
        run: node scripts/ci-patient-basic.js
      - name: Start app (background + readiness)
        run: |
          nohup npm start > app.log 2>&1 &
          echo $! > app.pid
          echo 'Process PID:' $(cat app.pid)
          # readiness loop (allows warming status)
          for i in $(seq 1 50); do
            code=$(curl -s -o health.json -w '%{http_code}' http://localhost:3000/api/health || echo 000)
            if [ "$code" = "200" ]; then
              echo "Health OK (200) em tentativa $i"; head -n 1 health.json; break
            fi
            if [ $((i % 5)) -eq 0 ]; then
              echo "Tentativa $i health=$code"; head -n 1 health.json || true; tail -n 20 app.log || true
            fi
            sleep 2
          done
          final=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:3000/api/health || echo 000)
          if [ "$final" != "200" ]; then
            echo 'Falha readiness. Últimas linhas log:'
            tail -n 120 app.log || true
            exit 1
          fi
      - name: Auth + RBAC + Export tests
        run: |
          node test-patients-auth.js
          node test-rbac-patients.js
          node test-export-zip-automated.js
      - name: Metrics snapshot (best effort)
        run: curl -fsS http://localhost:3000/api/metrics | head -n 40 || echo 'metrics unavailable'
      - name: Stop app
        if: always()
        run: |
          if [ -f app.pid ]; then kill $(cat app.pid) || true; fi
          sleep 1
      - name: Security quick audit
        run: npm run security:quick-audit
